package estoque2;

public class Material extends java.lang.Object implements java.lang.Cloneable{
	
	public State state;
	public Integer skuMaterial;
	public Integer unitMaterial;
	public Boolean registerStatus;
	private TelaCadastro adapter; 
	
	public Material(){
		state = State.Idle;
		registerStatus = false;
		skuMaterial = 0;
		unitMaterial = 0;
		
	}
	
	public Material clone(){
		Material cl = new Material();
		
		cl.state = this.state;
		cl.skuMaterial = this.skuMaterial;
		cl.unitMaterial = this.unitMaterial;
		cl.registerStatus = this.registerStatus;
		cl.adapter = this.adapter;
		
		return cl;
	}
	
	public void handleEvent(Object... in_colObject){
		if(in_colObject.length > 0){
			
			String sEventName = (String)in_colObject[0];
			if ((state == State.Idle) && (sEventName.compareTo("registerEvent") == 0)){
				//values generated by parteg
				//skuMaterial = ((Integer)in_colObject[1]).intValue();
				//unitMaterial = ((Integer)in_colObject[1]).intValue();
				
				state = State.Registering;
				
				}else  if((state == State.Registering) && (sEventName.compareTo("validEvent") == 0)) {
					skuMaterial = ((Integer)in_colObject[1]).intValue();
					unitMaterial = ((Integer)in_colObject[2]).intValue();
					
					registerStatus = registerIsValid(skuMaterial, unitMaterial);
					
					if(registerStatus == false){
						state = State.Registering;
					}else{
						//saveData(skuMaterial, unitMaterial);
						state = State.Registered;
					}
			
			}else if((state == State.Registered) && (sEventName.compareTo("newRegisterEvent") == 0)){
			
				state = State.Registering;
				
			}else if((state == State.Registered) && (sEventName.compareTo("finaliseEvent") == 0)){
				//closeSection();
				
			}
			
		}
	}
	
	protected Boolean registerIsValid(Integer sku, Integer unit){
		if(sku >= 1 && unit >= 1){
			return true;
		}else{
			return false;
		}
		
		//return adapter.appRegister(sku, unit);
	}
	protected void closeSection(){
		adapter.appCloseSection();
	}
	
	protected void saveData(Integer sku, Integer unit){
		adapter.appSaveData(sku, unit);
	}
}
