package estoque2;

public class Material extends java.lang.Object implements java.lang.Cloneable{
	
	public State state;
	public Integer skuMaterial;
	public Integer unitMaterial;
	public Boolean registerStatus;
	
	public Material(){
		state = State.Idle;
		registerStatus = false;
		skuMaterial = 0;
		unitMaterial = 0;
		
	}
	
	public Material clone(){
	}
	
	public void handleEvent(Object... in_colObject){
		if(in_colObject.length > 0){
			String sEventName = (String)in_colObject[0];
			if ((state == State.Idle) && (sEventName.compareTo("registerEvent") == 0)){
				//values generated by parteg
				skuMaterial = ((Integer)in_colObject[1]).intValue();
				unitMaterial = ((Integer)in_colObject[1]).intValue();
				
				state = State.Registering;
				
				}else  if((state == State.Registering) && (sEventName.compareTo("validEvent") == 0)) {
					skuMaterial = ((Integer)in_colObject[2]).intValue();
					unitMaterial = ((Integer)in_colObject[2]).intValue();
					
					registerStatus = registerIsValid(skuMaterial, unitMaterial);
					
					if(registerStatus == false){
						state = State.Registering;
					}else{
						state = State.Registered;
					}
			
			}else if((state == State.Registered) && (sEventName.compareTo("newRegisterEvent") == 0)){
				state = State.Registering;
				
			}else if((state == State.Registered) && (sEventName.compareTo("finaliseEvent") == 0)){
				closeSection();
				
			}
			
		}
	}
	
	//Acho que pedro/jesus criam o adapter
	protected Boolean registerIsValid(Integer skuPar, Integer unitPar){
		//return adapter.appLogin(sku, unit);
		return adapter.appRegister(sku, unit);
	}
	protected void closeSection(){
		adapter.appCloseSection();
	}
}
